name: CI

on:
  push: ~
  pull_request: ~
  schedule:
    - cron:  '0 12 * * *'

jobs:
  build_and_test:
    runs-on: [ubuntu-latest, windows-latest]
    strategy:
        fail-fast: false
        matrix:
          node-version: [12.x, 14.x]
  
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - name: Lint & Build & Test
        run: npm run all
